### ISSUE TITLE
Investigate and fix deprecation warning from `wasm-bindgen` 

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#3482]
After generating a new app using `pnpm create fuels` and running `fuels:dev` inside of it, we get:

```console
using deprecated parameters for the initialization function; pass a single object instead
```

> Ref: https://github.com/rustwasm/wasm-bindgen/issues/4122#issuecomment-2380562394

The fix/bump should probably be done on:
- https://github.com/FuelLabs/fuel-vm

**Comment by petertonysmith94** [comment]
The following [PR](https://github.com/FuelLabs/fuel-vm/pull/875) (merged) should resolve this issue.

We're awaiting the sequential bump and release of the next fuel-core version.

**Comment by arboleya** [comment]
Blocked by the above comment.

**Comment by petertonysmith94** [comment]
Dig some further digging and found that we're passing options incorrectly.

The following PR should resolve this:
- https://github.com/FuelLabs/fuel-vm/pull/903

**Comment by Torres-ssf** [comment]
> [@Torres-ssf](https://github.com/Torres-ssf) Did we manage to confirm if this issue is gone in [#3590](https://github.com/FuelLabs/fuels-ts/pull/3590)?

This problem was not fixed on `0.59.1`. And it seems there is no release for [0.59.2](https://www.npmjs.com/package/@fuels/vm-asm)

**Comment by petertonysmith94** [comment]
[https://github.com/FuelLabs/fuel-vm/blob/master/CHANGELOG.md](https://github.com/FuelLabs/fuel-vm/blob/master/CHANGELOG.md)<br>Looks like it's still in the unreleased pile
